version: "2"
services:
  chirpstack-gateway-bridge:
    build:
      context: .
      dockerfile: Dockerfile-devel
    ports:
      - "1700:1700/udp"
    volumes:
      - ./:/chirpstack-gateway-bridge
    links:
      - mosquitto
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883
      - TEST_MQTT_SERVER=tcp://mosquitto:1883

  mosquitto:
    image: eclipse-mosquitto
