# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/brocaar/loraserver"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/brocaar/lorawan"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  version = "v0.0.3"
  name = "github.com/spf13/cobra"

[[constraint]]
  version = "v1.0.2"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.0"
