baseURL = "https://www.chirpstack.io/gateway-bridge/"
languageCode = "en-us"
title = "ChirpStack Gateway Bridge documentation"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true
theme = "chirpstack-hugo-theme"

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-broadcast-tower'></i>"
    name = "Gateway installation"
    identifier = "gateway"
    url = "/gateway/"
    weight = 3

[[menu.main]]
	pre = "<i class='fas fa-cogs'></i>"
	name = "Backends"
	identifier = "backends"
	url = "/backends/"
	weight = 4

[[menu.main]]
	pre = "<i class='far fa-file-alt'></i>"
	name = "Payloads"
	identifier = "payloads"
	url = "/payloads/"
	weight = 5

[[menu.main]]
    pre = "<i class='fas fa-code'></i>"
    name = "Integrate"
    identifier = "integrate"
    url = "/integrate/"
    weight = 6

[[menu.main]]
    pre = "<i class='fas fa-chart-line'></i>"
    name = "Metrics"
    identifier = "metrics"
    url = "/metrics/"
    weight = 7

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 8

[params]
    version = "3.5.0"
	component = "chirpstack-gateway-bridge"
